# This is a basic workflow that is manually triggered

name: Run Tests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Test CentOS 6:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: "tests on centos6"
        id: centos6
        uses: test-centos6@master
